services:
  # NGINX (Entry point)
  nginx:
    image: nginx:1.28.1-alpine
    container_name: tsp-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app-python:
        condition: service_started
    restart: unless-stopped

  # PYTHON (Main Application Logic)
  app-python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: tsp-app-python
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      app-db:
        condition: service_healthy # Wait for DB to be fully ready
    restart: unless-stopped

  # POSTGRES (Database Engine)
  app-db:
    image: postgres:15-alpine
    container_name: tsp-app-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/.db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5